// Sav tekst sučelja na jednom mjestu (hrvatski/bosanski, ijekavica).

export const copy = {
  auth: {
    title: "Prijava",
    lead: "Prijavi se svojim emailom i lozinkom.",
    email: "Email",
    password: "Lozinka",
    submit: "Prijavi se",
    invalid: "Pogrešan email ili lozinka.",
    demoLead: "Ili uđi u demo:",
    signOut: "Odjava",
    notConfigured:
      "Supabase još nije povezan. Dodaj ključeve u .env.local, pa pokreni npm run db:migrate i npm run db:seed.",
  },

  nav: {
    member: {
      home: "Početna",
      program: "Program",
      assignments: "Zadaci",
      calls: "Pozivi",
      community: "Zajednica",
      progress: "Moj napredak",
    },
    staff: {
      cohort: "Kohorta",
      review: "Zadaci za pregled",
      questions: "Pitanja",
      program: "Program",
      calls: "Pozivi",
    },
  },

  home: {
    greeting: (name: string) => `Dobrodošla nazad, ${name}.`,
    whereYouAre: "Gdje si sada",
    nextLesson: "Sljedeća lekcija",
    continueLesson: "Nastavi lekciju",
    allDone: "Prošla si sve otključane lekcije. Sljedeći modul se otvara uskoro.",
    openAssignment: "Otvoreni zadatak",
    noOpenAssignment: "Nemaš otvorenih zadataka.",
    nextCall: "Sljedeći poziv",
    noNextCall: "Sljedeći poziv još nije zakazan.",
    askQuestion: "Postavi pitanje",
    joinZoom: "Uđi na Zoom",
    notices: "Poruka od tima",
  },

  reflection: {
    title: "Sedmična refleksija",
    lead: "Tri kratka pitanja. Andreja ih čita prije poziva.",
    win: "Šta je ovu sedmicu uspjelo?",
    blocker: "Šta te koči?",
    nextStep: "Koji je sljedeći korak?",
    submit: "Spremi refleksiju",
    done: "Hvala, vidimo se na pozivu.",
    already: "Refleksiju za ovu sedmicu si već poslala.",
    edit: "Uredi",
  },

  program: {
    title: "Program",
    lead: "Osam modula. Novi se otključava po rasporedu kohorte.",
    locked: (date: string) => `Otključava se ${date}`,
    lockedShort: "Zaključano",
    completed: "Završeno",
    pickLesson: "Odaberi lekciju s lijeve strane.",
    worksheet: "Preuzmi radni list (PDF)",
    markDone: "Označi kao završeno",
    markedDone: "Završeno",
    undo: "Poništi",
    duration: (min: number) => `${min} min`,
    discussion: "Diskusija",
    discussionEmpty: "Još nema komentara ispod ove lekcije. Budi prva.",
    commentPlaceholder: "Napiši pitanje ili misao…",
    send: "Objavi",
    reply: "Odgovori",
    coachLabel: "Andreja",
    lockedBody: "Ova lekcija još nije otključana.",
  },

  assignments: {
    title: "Zadaci",
    lead: "Jedan zadatak po modulu. Predaješ tekstom, po želji dodaš fajl.",
    empty: "Još nema zadataka.",
    statusOpen: "Otvoren",
    statusPending: "Predan · čeka pregled",
    statusReviewed: "Pregledan",
    overdue: "Kasni",
    yourAnswer: "Tvoj odgovor",
    bodyPlaceholder: "Napiši svoj odgovor…",
    file: "Dodaj fajl (PDF ili slika, do 5 MB)",
    submit: "Predaj",
    resubmit: "Pošalji ponovo",
    submitted: (date: string) => `Predano ${date}`,
    feedbackTitle: "Povratna informacija",
    feedbackFrom: (name: string, date: string) => `${name} · ${date}`,
    waiting: "Predano. Javit ćemo se s povratnom informacijom.",
    locked: "Zadatak se otvara kad se otključa modul.",
    attachment: "Priloženi fajl",
  },

  calls: {
    title: "Pozivi",
    lead: "Sedmični Zoom poziv s Andrejom.",
    next: "Sljedeći poziv",
    past: "Prošli pozivi",
    pastEmpty: "Još nema snimaka.",
    recording: "Pogledaj snimak",
    notes: "Bilješke s poziva",
    myQuestions: "Moja pitanja",
    myQuestionsEmpty: "Još nisi postavila pitanje.",
    askTitle: "Postavi pitanje za ovaj poziv",
    askPlaceholder: "Šta bi htjela da Andreja objasni?",
    ask: "Pošalji pitanje",
    answered: "Odgovoreno",
    waitingAnswer: "Čeka odgovor",
    noZoom: "Zoom link stiže dan prije poziva.",
  },

  community: {
    title: "Zajednica",
    lead: "Zadnje diskusije ispod lekcija. Da vidiš da program živi.",
    empty: "Još nema komentara.",
    inLesson: "u lekciji",
  },

  progress: {
    title: "Moj napredak",
    lead: "Gdje si prošla i šta si predala.",
    modules: "Moduli",
    lessonsPct: (pct: number) => `${pct}% lekcija`,
    submissionsCount: (n: number) => `${n} predanih zadataka`,
    diary: "Dnevnik programa",
    diaryLead: "Sve tvoje refleksije, od najnovije.",
    diaryEmpty: "Još nema refleksija. Prvu možeš napisati na Početnoj.",
    weekOf: (date: string) => `Sedmica od ${date}`,
  },

  cohort: {
    title: "Kohorta",
    lead: (name: string) => `${name} · pregled cijele grupe.`,
    statMembers: "Članica u programu",
    statActive: "Aktivnih ove sedmice",
    statToReview: "Zadataka za pregled",
    statStalled: "Stale",
    layout: "Raspored kohorte",
    layoutLead: "Ko je u kojem modulu. Crvena tačka = stala.",
    layoutEmpty: "Nema članica u ovom modulu.",
    table: "Sve članice",
    colName: "Ime",
    colModule: "Modul",
    colLessons: "% lekcija",
    colDays: "Dana od aktivnosti",
    colOverdue: "Kasni",
    colStatus: "Status",
    colAssistant: "Asistentica",
    filterAll: "Sve",
    filterSlowing: "Usporile",
    filterStalled: "Stale",
    filterMine: "Moje",
    remind: "Pošalji podsjetnik",
    remindAllStalled: "Pošalji svim stalim",
    remindDone: (n: number) => `Podsjetnik poslan: ${n}`,
    remindEmpty: "Nema kome poslati.",
    selected: (n: number) => `${n} odabrano`,
    empty: "Nema članica koje odgovaraju filteru.",
    noAssistant: "—",
  },

  status: {
    active: "Aktivna",
    slowing: "Usporila",
    stalled: "Stala",
  },

  review: {
    title: "Zadaci za pregled",
    lead: "Red čekanja, najstarije prvo.",
    empty: "Nema predaja koje čekaju pregled. Čisto.",
    from: "Predala",
    assignment: "Zadatak",
    answer: "Odgovor",
    feedbackPlaceholder: "Napiši povratnu informaciju…",
    markReviewed: "Označi pregledano",
    reviewed: "Pregledano",
    openFile: "Otvori priloženi fajl",
  },

  questions: {
    title: "Pitanja za poziv",
    lead: "Pitanja za sljedeći poziv, grupisana po modulu.",
    empty: "Nema pitanja za sljedeći poziv.",
    answerPlaceholder: "Napiši odgovor koji će članica vidjeti…",
    save: "Spremi odgovor",
    markAnswered: "Odgovoreno",
    noCall: "Nema zakazanog poziva.",
    ungrouped: "Bez modula",
  },

  editor: {
    programTitle: "Program",
    programLead: "Moduli, lekcije i zadaci. Obična forma, bez prevlačenja.",
    callsTitle: "Pozivi",
    callsLead: "Zakaži poziv, poslije dodaj snimak i bilješke.",
    moduleTitle: "Naslov modula",
    moduleSubtitle: "Podnaslov",
    moduleUnlock: "Otključava se",
    moduleSummary: "Sažetak (markdown)",
    lessonTitle: "Naslov lekcije",
    lessonVideo: "Video URL",
    lessonBody: "Tekst lekcije (markdown)",
    lessonDuration: "Trajanje (min)",
    lessonWorksheet: "Radni list (PDF)",
    assignmentTitle: "Naslov zadatka",
    assignmentInstructions: "Upute (markdown)",
    assignmentDue: "Rok",
    newLesson: "Nova lekcija",
    newAssignment: "Novi zadatak",
    newCall: "Novi poziv",
    callTitle: "Naslov",
    callDate: "Datum i vrijeme",
    callZoom: "Zoom URL",
    callRecording: "URL snimka",
    callNotes: "Bilješke (markdown)",
    save: "Spremi",
    saved: "Spremljeno.",
    preview: "Pregled",
    write: "Pisanje",
    adminOnly: "Ovaj dio vidi samo Andreja.",
  },

  memberProfile: {
    back: "Nazad na kohortu",
    joined: (date: string) => `U programu od ${date}`,
    assistant: (name: string) => `Asistentica: ${name}`,
    modulesTitle: "Napredak po modulima",
    timeline: "Hronologija",
    timelineEmpty: "Još nema aktivnosti.",
    kindSubmission: "Predaja",
    kindComment: "Komentar",
    kindReflection: "Refleksija",
    kindQuestion: "Pitanje",
    kindLesson: "Završena lekcija",
  },

  common: {
    loading: "Učitavam…",
    error: "Nešto je pošlo po zlu. Pokušaj ponovo.",
    cancel: "Odustani",
    optional: "neobavezno",
    module: (n: number) => `Modul ${n}`,
    lesson: (n: number) => `Lekcija ${n}`,
    of: "od",
    lessonsOf: (done: number, total: number) => `${done} od ${total} lekcija`,
  },
} as const;
