// Every string in the interface lives here.

export const copy = {
  auth: {
    title: "Sign in",
    lead: "Sign in with your email and password.",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    invalid: "Wrong email or password.",
    demoLead: "Or step into the demo:",
    signOut: "Sign out",
    notConfigured:
      "Supabase isn't connected yet. Add your keys to .env.local, then run npm run db:migrate and npm run db:seed.",
  },

  nav: {
    member: {
      home: "Home",
      program: "Programme",
      assignments: "Assignments",
      calls: "Calls",
      community: "Community",
      progress: "My progress",
    },
    staff: {
      cohort: "Cohort",
      review: "To review",
      questions: "Questions",
      program: "Programme",
      calls: "Calls",
    },
  },

  home: {
    greeting: (name: string) => `Welcome back, ${name}.`,
    whereYouAre: "Where you are",
    nextLesson: "Next lesson",
    continueLesson: "Continue lesson",
    allDone: "You've finished every unlocked lesson. The next module opens soon.",
    openAssignment: "Open assignment",
    noOpenAssignment: "Nothing waiting on you right now.",
    nextCall: "Next call",
    noNextCall: "The next call hasn't been scheduled yet.",
    askQuestion: "Ask a question",
    joinZoom: "Join on Zoom",
    notices: "A note from the team",
    journey: "Where you are in the programme",
    journeyLead: (done: number, total: number) => `${done} of ${total} unlocked lessons`,
    latest: "Latest from the community",
    latestAll: "All discussions",
  },

  reflection: {
    title: "Weekly reflection",
    lead: "Three short questions. Andreja reads them before the call.",
    win: "What worked this week?",
    blocker: "What's getting in the way?",
    nextStep: "What's your next step?",
    submit: "Save reflection",
    done: "Thank you — see you on the call.",
    already: "You've already sent this week's reflection.",
    edit: "Edit",
  },

  program: {
    title: "Programme",
    lead: "Eight modules. A new one unlocks on the cohort's schedule.",
    locked: (date: string) => `Unlocks ${date}`,
    lockedShort: "Locked",
    completed: "Completed",
    pickLesson: "Pick a lesson from the list on the left.",
    worksheet: "Download worksheet (PDF)",
    markDone: "Mark as complete",
    markedDone: "Completed",
    undo: "Undo",
    duration: (min: number) => `${min} min`,
    discussion: "Discussion",
    discussionEmpty: "No comments under this lesson yet. Be the first.",
    commentPlaceholder: "Write a question or a thought…",
    send: "Post",
    reply: "Reply",
    coachLabel: "Andreja",
    lockedBody: "This lesson hasn't unlocked yet.",
    videoPlaceholder: "The lesson recording goes here.",
    videoPlaceholderHint: "Andreja adds a YouTube or Vimeo link in the programme editor.",
  },

  assignments: {
    title: "Assignments",
    lead: "One assignment per module. Write your answer, attach a file if you want.",
    empty: "No assignments yet.",
    statusOpen: "Open",
    statusPending: "Submitted · awaiting review",
    statusReviewed: "Reviewed",
    overdue: "Overdue",
    yourAnswer: "Your answer",
    bodyPlaceholder: "Write your answer…",
    file: "Attach a file (PDF or image, up to 5 MB)",
    submit: "Submit",
    resubmit: "Send again",
    submitted: (date: string) => `Submitted ${date}`,
    feedbackTitle: "Feedback",
    feedbackFrom: (name: string, date: string) => `${name} · ${date}`,
    waiting: "Submitted. We'll come back to you with feedback.",
    locked: "This opens when the module unlocks.",
    attachment: "Attached file",
  },

  calls: {
    title: "Calls",
    lead: "The weekly Zoom call with Andreja.",
    next: "Next call",
    past: "Past calls",
    pastEmpty: "No recordings yet.",
    recording: "Watch the recording",
    notes: "Call notes",
    myQuestions: "My questions",
    myQuestionsEmpty: "You haven't asked anything yet.",
    askTitle: "Ask a question for this call",
    askPlaceholder: "What would you like Andreja to explain?",
    ask: "Send question",
    answered: "Answered",
    waitingAnswer: "Awaiting an answer",
    noZoom: "The Zoom link arrives the day before the call.",
  },

  community: {
    title: "Community",
    lead: "The latest discussions under the lessons. Not a forum — just proof the programme is alive.",
    empty: "No comments yet.",
    inLesson: "in the lesson",
  },

  progress: {
    title: "My progress",
    lead: "Where you've been and what you've handed in.",
    modules: "Modules",
    lessonsPct: (pct: number) => `${pct}% of lessons`,
    submissionsCount: (n: number) => `${n} assignments submitted`,
    diary: "Programme diary",
    diaryLead: "Every reflection you've written, newest first.",
    diaryEmpty: "No reflections yet. You can write your first one on the Home screen.",
    weekOf: (date: string) => `Week of ${date}`,
  },

  cohort: {
    title: "Cohort",
    lead: (name: string) => `${name} · the whole group at a glance.`,
    statMembers: "Members enrolled",
    statActive: "Active this week",
    statToReview: "Assignments to review",
    statStalled: "Stalled",
    layout: "Cohort map",
    layoutLead: "Who is in which module. A red dot means stalled.",
    layoutEmpty: "Nobody in this module.",
    table: "All members",
    colName: "Name",
    colModule: "Module",
    colLessons: "% of lessons",
    colDays: "Since last activity",
    colOverdue: "Overdue",
    colStatus: "Status",
    colAssistant: "Assistant",
    filterAll: "All",
    filterSlowing: "Slowing",
    filterStalled: "Stalled",
    filterMine: "Mine",
    remind: "Send a nudge",
    remindAllStalled: "Nudge everyone stalled",
    remindDone: (n: number) => `Nudge sent to ${n}`,
    remindEmpty: "Nobody to nudge.",
    reminderBody:
      "We missed you this week. Open the next lesson whenever you can — and tell us if something is getting in the way.",
    selected: (n: number) => `${n} selected`,
    empty: "No members match this filter.",
    noAssistant: "—",
    railDays: (n: number | null) => (n === null ? "no activity" : `${n} days`),
    railOverdue: (n: number) => `${n} overdue`,
  },

  status: {
    active: "Active",
    slowing: "Slowing",
    stalled: "Stalled",
  },

  review: {
    title: "Assignments to review",
    lead: "The queue, oldest first.",
    empty: "Nothing waiting for review. All clear.",
    from: "Submitted by",
    assignment: "Assignment",
    answer: "Answer",
    feedbackPlaceholder: "Write your feedback…",
    markReviewed: "Mark as reviewed",
    reviewed: "Reviewed",
    openFile: "Open attached file",
    totalReviewed: "reviewed in total",
  },

  questions: {
    title: "Questions for the call",
    lead: "Questions for the next call, grouped by module.",
    empty: "No questions for the next call.",
    answerPlaceholder: "Write the answer the member will see…",
    save: "Save answer",
    markAnswered: "Answered",
    noCall: "No call scheduled.",
    ungrouped: "No module",
  },

  editor: {
    programTitle: "Programme",
    programLead: "Modules, lessons and assignments. Plain forms, no drag and drop.",
    callsTitle: "Calls",
    callsLead: "Schedule a call, then add the recording and notes afterwards.",
    moduleTitle: "Module title",
    moduleSubtitle: "Subtitle",
    moduleUnlock: "Unlocks on",
    moduleSummary: "Summary (markdown)",
    lessonTitle: "Lesson title",
    lessonVideo: "Video URL",
    lessonBody: "Lesson text (markdown)",
    lessonDuration: "Length (min)",
    lessonWorksheet: "Worksheet (PDF)",
    assignmentTitle: "Assignment title",
    assignmentInstructions: "Instructions (markdown)",
    assignmentDue: "Due date",
    newLesson: "New lesson",
    newAssignment: "New assignment",
    newCall: "New call",
    callTitle: "Title",
    callDate: "Date and time",
    callZoom: "Zoom URL",
    callRecording: "Recording URL",
    callNotes: "Notes (markdown)",
    save: "Save",
    saved: "Saved.",
    preview: "Preview",
    write: "Write",
    adminOnly: "Only Andreja sees this.",
    callsSummary: (past: number, scheduled: boolean) =>
      `${past} past · ${scheduled ? "1 scheduled" : "none scheduled"}`,
    lessonCount: (n: number) => `${n} ${n === 1 ? "lesson" : "lessons"}`,
  },

  memberProfile: {
    back: "Back to the cohort",
    joined: (date: string) => `In the programme since ${date}`,
    assistant: (name: string) => `Assistant: ${name}`,
    modulesTitle: "Progress by module",
    timeline: "Timeline",
    timelineEmpty: "No activity yet.",
    kindSubmission: "Submission",
    kindComment: "Comment",
    kindReflection: "Reflection",
    kindQuestion: "Question",
    kindLesson: "Lesson completed",
  },

  roles: {
    member: "Member",
    assistant: "Assistant",
  },

  common: {
    loading: "Working…",
    error: "Something went wrong. Please try again.",
    cancel: "Cancel",
    optional: "optional",
    module: (n: number) => `Module ${n}`,
    lesson: (n: number) => `Lesson ${n}`,
    of: "of",
    lessonsOf: (done: number, total: number) => `${done} of ${total} lessons`,
  },
} as const;
